Add timeout and video download
openvinotoolkit/mediapipe pull request #26
Opened 2023-09-08 11:34 UTC by rasapala

2023-09-08 12:25 UTC, dtrawins requested changes

2023-09-08 12:25 UTC, dtrawins commented on mediapipe/calculators/ovms/modelapiovmssessioncalculator.cc
> +            int timeoutCounter = 100;
timeout for readiness is not a good option because loading time depends on the model.

2023-09-11 11:07 UTC, atobiszei approved these changes

2023-09-11 11:44 UTC, dtrawins approved these changes

2023-09-11 11:48 UTC, merged